# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='score',
            field=models.CharField(default='Not Run yet', max_length=10),
        ),
    ]
