# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='title',
            new_name='class_number',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='author',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='text',
            new_name='submit_content',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='published_date',
            new_name='submit_time',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='created_date',
        ),
        migrations.AddField(
            model_name='submit',
            name='homework_number',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
