# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancient', '0003_auto_20180129_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='test_output',
        ),
    ]
