# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ancient', '0003_classchoose_classtable_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
        migrations.AddField(
            model_name='homework',
            name='class_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ancient.ClassTable'),
        ),
        migrations.AlterField(
            model_name='classchoose',
            name='class_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ancient.ClassTable'),
        ),
        migrations.AlterField(
            model_name='classtable',
            name='class_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='homework_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='submit',
            name='class_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ancient.ClassTable'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='homework_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ancient.Homework'),
        ),
    ]
