# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ancient', '0004_remove_homework_test_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='test_input',
        ),
    ]
