# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ancient', '0006_auto_20180129_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='test_input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='test_output',
            field=models.TextField(),
        ),
    ]
